branch-defaults:
  default:
    environment: planpassive-aws
  master:
    environment: planpassive-aws
    group_suffix: null
environment-defaults:
  planpassive-aws:
    branch: null
    repository: null
global:
  application_name: nodejs-v1
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
